version: '3.8'

services:
  frontend:
    build:
      context: ./src
      dockerfile: dockerfile
    ports:
      - "5174:5174"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000

  backend:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "8001:8000"  # Changed host port to 8001 to avoid conflict
    environment:
      - PORT=8000
      - MONGO_URL=mongodb+srv://antidoteTranscribe:dQrYiafUGuuUbGWR@cluster0.f7fkxds.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
