version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "4173:4173"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://backend:8000

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - PORT=8000
      - MONGO_URL=${MONGO_URL}
      
