version: 2.1
jobs:
  build frontend:
    docker:
      - image: circleci/buildpack-deps:bullseye
    environment:
      IMAGE_NAME: alexcampo3695/react-audio-recorder-frontend
    working_directory: ~/frontend
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CIRCLE_SHA1
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$CIRCLE_SHA1

  build-backend:
    docker:
      - image: circleci/buildpack-deps:bullseye
    environment:
      IMAGE_NAME: alexcampo3695/react-audio-recorder-backend
    working_directory: ~/backend
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image for backend
          command: |
            docker build -t $IMAGE_NAME:latest -f server/Dockerfile .
      - run:
          name: Push Docker Image for backend
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CIRCLE_SHA1
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$CIRCLE_SHA1

  workflows:
    version: 2
    build-deploy-master:
      jobs:
        - build-frontend:
            filters:
              branches:
                only: master
        - build-backend:
            filters:
              branches:
                only: master
        - deploy:
            requires:
              - build-frontend
              - build-backend
            filters:
              branches:
                only: master
# workflows:
#   version: 2
#   build-deploy-master:
#     jobs:
#       - build:
#           filters:
#             branches:
#               only: master
