version: 2.1
jobs:
  # Job to build and push the frontend Docker image
  build-frontend:
    docker:
      - image: circleci/buildpack-deps:bullseye
    environment:
      IMAGE_NAME: alexcampo3695/react-audio-recorder-frontend
    working_directory: ~/frontend
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CIRCLE_SHA1
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$CIRCLE_SHA1

  # Job to build and push the backend Docker image
  build-backend:
    docker:
      - image: circleci/buildpack-deps:bullseye
    environment:
      IMAGE_NAME: alexcampo3695/react-audio-recorder-backend
    working_directory: ~/backend
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image for backend
          command: |
            docker build -t $IMAGE_NAME:latest -f server/Dockerfile .
      - run:
          name: Push Docker Image for backend
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CIRCLE_SHA1
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$CIRCLE_SHA1

  # Job to deploy the application
  deploy:
    docker:
      - image: circleci/buildpack-deps:bullseye
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install envsubst
          command: |
            sudo apt-get update && sudo apt-get -y install gettext-base
      - run:
          name: Install kubectl
          command: |
            curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod u+x ./kubectl
      - run:
          name: Deploy Code
          command: ./scripts/ci-deploy.sh

workflows:
  version: 2
  build-deploy-master:
    jobs:
      - build-frontend:
          filters:
            branches:
              only: master
      - build-backend:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build-frontend
            - build-backend
          filters:
            branches:
              only: master