# Use the official node image as the base image for x86_64
FROM --platform=linux/amd64 node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy the rest of the application code to the container
COPY server .

# Set the environment to production
ENV NODE_ENV=production

# Set the PORT environment variable
ENV PORT=8002

# Expose the port the app runs on
EXPOSE 8002

# Build the TypeScript code
RUN npm run build

# Start the server
CMD ["npm", "run", "start"]
