# Use the official node image as the base image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json from the server directory to the working directory
COPY package.json package-lock.json ./

# Install the dependencies
RUN npm install --legacy-peer-deps

# Copy the rest of the application code to the working directory
COPY . .

# Set environment variables
ENV PORT=8001

# Expose the port the app runs on
EXPOSE 8001

# Start the server
CMD ["npm", "run", "dev"]
