apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  selector:
    matchLabels:
      app: client
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: client
        tier: frontend
        track: stable
    spec:
      containers:
        - name: nginx
          image: alexcampo3695/react-audio-recorder-frontend:latest
          env:
            - name: VITE_PROD_BACKEND_URL
              value: "http://server.default.svc.cluster.local:8002"
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/frontend-nginx.conf
              subPath: frontend-nginx.conf
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
            items:
              - key: frontend-nginx.conf
                path: frontend-nginx.conf
