
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
...