apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: default
  labels:
    app: server
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8001
      name: http
  selector:
    app: server
